version: '3.4'
services:

  app:
    container_name: slackbot
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 80
    ports:
      - "7171:80"
    build:
      context: .
    environment:
      DEBUG: "true"
      ENVIRONMENT: ${ENVIRONMENT:-local}
    volumes:
      - ./app:/app
    env_file: .env


